export const IPC_CHANNELS = {
  appGetInfo: "app:get-info",
  sessionGetState: "session:get-state",
  workspaceGetState: "workspace:get-state",
  workspaceOpen: "workspace:open",
  workspaceOpenCurrent: "workspace:open-current",
  workspaceSelect: "workspace:select",
  timelineGetState: "timeline:get-state",
  threadSelect: "thread:select",
  turnStart: "turn:start",
  turnInterrupt: "turn:interrupt",
  approvalRespond: "approval:respond",
  userInputSubmit: "user-input:submit",
  realtimeGetState: "realtime:get-state",
  realtimeStart: "realtime:start",
  realtimeStop: "realtime:stop",
  realtimeAppendAudio: "realtime:append-audio",
  realtimeAppendText: "realtime:append-text",
  realtimeEvent: "realtime:event",
} as const;
